### ISSUE TITLE
PVP compliance

### ISSUE THREAD

**Issue by hvr** [jwvg0425/d3d11binding#1]
I've noticed uploads of this package to Hackage which appear not to adhere to the [PVP](https://wiki.haskell.org/Package_versioning_policy). Complying with the PVP (which is different from SemVer) is one of the few guidelines packages uploaded to http://hackage.haskell.org/  are expected to follow.

Specifically, I see a series of versions up to version 0.0.0.7 which each appears to add new modules or exported symbols, so this would at the very least require minor version bumps (i.e. incrementing the 3rd version component, rather than the 4th), if not more.

**Comment by jwvg0425** [comment]
oh, I didn't know much about PVP. I will follow that guideline next version of this package. thank you for your kindness.
